export const tasks = [
  {
    id: 'id1',
    isPlanned: true,
    isDone: true,
    title: 'Buy products for the dinner with some interesting drinks. So here is also a long title',
    prefix: 'OTHER',
    estimation: 0.5,
  },
  {
    id: 'id2',
    isPlanned: true,
    isDone: true,
    title: 'Finish story with facets',
    prefix: 'EPAM',
    estimation: 3,
  },
  {
    id: 'id3',
    isPlanned: true,
    isDone: true,
    title: 'Meeting with Vlad',
    prefix: 'RAKURS',
    estimation: 1,
  },
  {
    id: 'id4',
    isPlanned: false,
    isDone: true,
    title: 'Read book',
    prefix: 'OTHER',
    estimation: 1,
  },
  {
    id: 'id5',
    isPlanned: true,
    isDone: false,
    title: 'Creat new patterns of beat',
    prefix: 'MUSIC',
    estimation: 2,
  },
  {
    id: 'id6',
    isPlanned: true,
    isDone: false,
    title: 'Send photos to the cloud',
    prefix: 'OTHER',
    estimation: 0.5,
  },
  {
    id: 'id7',
    isPlanned: false,
    isDone: false,
    title: 'Go the the GYM',
    prefix: 'OTHER',
    estimation: 3,
  }
];